### ISSUE TITLE
MAX_INPUT_SET_SIZE seems to be twice as big as needed

### ISSUE THREAD

**Issue by pbudziszewski** [Jess-Ferguson/huffman#10]
#define MAX_INPUT_SET_SIZE 2 << 8 /* The input can contain at most 2 << 8 unique bytes */ 

I might not be understanding something, but it seems to me that (2 << 8 ) == 512 when you really only need 256

**Comment by Jess-Ferguson** [comment]
Fixed in 06aeedc

Thanks for the comment :)
